.TH QTSCROB 1 "April 23, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
qtscrob \- a last.fm and libre.fm submitter for portable devices
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "SYNOPSIS"
.B qtscrob
.RI [ options ]
.br
.SH "OPTIONS" 
This program follows the usual GNU command line syntax, with long
options starting with two dashes ('-').
A summary of options is included below.
.TP
.B \-c, \-\-config
Optional location of the config file. If this is not specified, then
.B qtscrob
will use the default platform specific location for its config file, e.g. 
~/.config/qtscrob.conf on Linux, the Registry on Windows, etc. Specifying
a config location allows
.B qtscrob
to run in a portable mode.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-verbose <level>
Output verbosity level
.br
.SH "DESCRIPTION"
.B QTScrobbler
is a program to submit information about tracks which have been listened to
from a portable music player to last.fm (previously known as Audioscrobbler),
libre.fm and/or a custom site of your choice.
.B QTScrobbler
can read this information from .scrobbler.log files (i.e. produced by the
open Rockbox firmware), from iPod databases, or from devices that use MTP
(aka Plays for Sure).
In addition to this,
.B QTScrobbler
can adjust the date/time information relating to when the track was listened
to before uploading.  This can be useful if your device is set to a different
timezone to the machine you upload from.
.B QTScrobbler
also allows you to view and edit the track information before uploading.
.br
.SH WWW
http://qtscrob.sourceforge.net
.br
.PP
This manual page was written by Robert Keevil <rkeevil@gmail.com>,
and is licensed under version 2 of the GPL.

